apiVersion: apps/v1
kind: Deployment
metadata:
  name: addition
  namespace: addition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addition
  template:
    metadata:
      labels:
        app: addition
    spec:
      containers:
        - name: addition
          image: bogdanserdinov/infra-example:1.1.0
          command: [ "/bin/sh", "-c", "addition" ]
          ports:
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: addition-config
          livenessProbe:
            httpGet:
              path: /heathz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m          # 1% of a CPU core
              memory: 32Mi      # 32 MB of memory
            limits:
              cpu: 100m         # 10% of a CPU core
              memory: 128Mi     # 128 MB of memory
